server:
  port: 9090
spring:
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_trans: true
  h2:
    console:
      path: /h2-console
      enabled: true